### ISSUE TITLE
Frontend new study: Save and add media does not work

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#459] opened 2015-02-06 06:54 UTC
In the tab 'Media Files for this Study' there is a link 'Click to Save and Add a Media File'. This does not save the study nor jump to the media edit form. Instead of the media for a page is displayed:
**The requested page cannot be found.**
500 **Layout default not found** 

A curious URL shows up in the browser URL line: http://localhost/j33_test/index.php/component/biblestudy/messageform#
(If I add a new media, the URL looks like: http://localhost/j33_test/index.php/medien-admin/mediafileform?layout=edit&return=aHR0cDovL2xvY2FsaG9zdC9qMzNfdGVzdC9pbmRleC5waHA/b3B0aW9uPWNvbV9iaWJsZXN0dWR5JnZpZXc9bWVkaWFmaWxlbGlzdA==)

**Comment by bcordis** [comment] 2015-05-10 00:29
@st-anton @tomfuller2 Please see fix and test.

**Comment by st-anton** [comment] 2015-05-11 19:29
Still same behaviour.

**Comment by bcordis** [comment] 2015-05-11 19:47
Did you clear your cache. I'm not able to reproduce the error now. I'll check again but this was fixed.

**Comment by st-anton** [comment] 2015-05-12 03:41
I tested with Firefox and IE, cleared the cache of both before, reloaded the page again.
Still the 500 error is present on both.

**Comment by bcordis** [comment] 2015-05-20 10:34
This is a design and will have to change if needed.

**Comment by st-anton** [comment] 2015-05-29 15:52
Now the 'save and add media file' does not crash anymore, the study is saved.
But afterwards, it does not open the same study in order to add a media file, but starts a new study to fill in.

**Comment by bcordis** [comment] 2015-08-05 00:31
@st-anton Can you verify this is still happening?

**Comment by st-anton** [comment] 2015-08-17 22:22
Yes, still happening.

**Comment by bcordis** [comment] 2015-08-17 22:30
Well that is not good. I'll look into where this is coming from. Need to fix this ASAP.

**Comment by tomfuller2** [comment] 2015-09-25 02:44
So now when I am editing a study on the front end, the # links do not work - it only stays on the first window and won't go to Media Files or Access or anything.

**Comment by tomfuller2** [comment] 2015-11-01 00:10
This now works so I am closing. Successfully added a study and media file. 
One thing we might consider is putting a Save button, not just Save & Close.

**Closed by tomfuller2** 2015-11-01 00:10 UTC
Labels: Accepted, Bug-Blocker

**Comment by bcordis** [comment] 2015-11-01 00:41
@tomfuller2 Save should show up when you are editing a existing one but it will not work from when adding new one from a sermon.
