### ISSUE TITLE
Frontend and Backend Study edit: Topics are not found

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#452] opened 2015-02-06 06:19 UTC
Editing a Study in the backend, no topic can be found. Thus no topic can be added to a study.

**Comment by st-anton** [comment] 2015-02-06 06:46
Also see #458 for missing field in the frontend

**Comment by st-anton** [comment] 2015-02-09 17:28
Does still not work; both in backend and frontend: No topic is found

**Comment by bcordis** [comment] 2015-02-10 00:00
@st-anton What browser are you testing on and cane you upload your test db so we i may test?

**Comment by st-anton** [comment] 2015-02-10 22:55
I tested with a new installation, no further database changes.
Both Firefox 35  and IE 11 show this.

**Comment by bcordis** [comment] 2015-02-16 21:39
@tomfuller2 Not sure on this one but not seeing how this works. Can you look into this?

**Comment by tomfuller2** [comment] 2015-02-18 04:19
I'm using Firefox 35.0.1 and I can see topics but they don't save.

**Comment by bcordis** [comment] 2015-02-18 04:28
@tomfuller1 ok I'll look and make sure save is working right.

**Comment by bcordis** [comment] 2015-02-21 21:50
@st-anton @tomfuller2 re test please also test adding new topics.

**Comment by tomfuller2** [comment] 2015-02-26 20:17
This now works. You can add topics from the list or add a topic in the
Topic view and then it will add and save in the study.

**Comment by st-anton** [comment] 2015-03-03 22:45
Works partly: Add new topic and finding the topic does work.
Also the bsms_studytopics tabe is saved. BUT: Columns bsms_studytopics->study_id and bsms_studytopics->asset_id are always 0. With this, the topics cannot be linked to the study.

**Comment by bcordis** [comment] 2015-03-04 00:15
Ok I'll look into this more.

**Comment by st-anton** [comment] 2015-03-22 21:23
Backend does work as expected.
Frontend puts the topics to the db.
But editing a study in the frontend with topics gets an empty field; the topics already set in the db are not displayed und subsequently deleted in the db when saving the study.

**Comment by tomfuller2** [comment] 2015-03-23 23:44
Agreed. Front end does not show topics that have been applied on backend. 
@bcordis you or @genu will have to look at this - this is beyond my capabilities.

**Comment by bcordis** [comment] 2015-05-09 22:38
@tomfuller2 Looking into the db problem for topics.

**Comment by bcordis** [comment] 2015-05-09 23:03
@tomfuller2 @st-anton I'm not seeing any errors in this can you show me some steps to reproduce the errors of the study not saving??

**Comment by bcordis** [comment] 2015-05-10 16:37
@st-anton Right now i'm not able to reproduce the bug. Need to have someone retest. so i can close this out.

**Comment by st-anton** [comment] 2015-05-11 19:15
Simple to reproduce:
- Add some topics to a study in the backend (I entered two topics); save and close
- open the study again; see that the topics are still there
- have a look in the _studytopics table: **All topics are entered twice!**
![topic1](https://cloud.githubusercontent.com/assets/2517417/7572440/5ccb9496-f81e-11e4-98be-add2102ab8ec.png)

- Open the same study in the frontend admin study view
- See, that the topics are not there.
- enter some new topics and save (I entered two different topics)
- Again, all topics are entered twice in the database:
![topic2](https://cloud.githubusercontent.com/assets/2517417/7572518/112b2316-f81f-11e4-853a-a5f75895b286.png)

So we have two bugs:
- two entries in the database
- frontend admin study does not detect the topics and thus does not save them subsequently

**Comment by bcordis** [comment] 2015-05-15 01:42
@st-anton Can this be a bug in your php. I'm not able to reproduce this. Can you tell me your states so i my try and create the closes environment.

**Comment by bcordis** [comment] 2015-05-20 10:32
Re testing this.

**Comment by st-anton** [comment] 2015-05-22 20:25
Exactly the situation I described up there (https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/452#issuecomment-101020517). 
Happens on the database and the code I just sent you.

**Comment by bcordis** [comment] 2015-05-23 03:02
@st-anton Please retest as i have found the bug.

**Comment by st-anton** [comment] 2015-05-23 10:50
Unfortunatelly not fixed

**Comment by bcordis** [comment] 2015-05-23 12:10
Looking more. Bad bug.

On Saturday, May 23, 2015, st-anton <notifications@github.com> wrote:

> Unfortunatelly not fixed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/452#issuecomment-104881823>
> .
>


-- 
Sent from Gmail Mobile

**Comment by st-anton** [comment] 2015-06-02 19:23
Now the same happens on the backend.

**Comment by bcordis** [comment] 2015-07-25 23:04
@st-anton This should be fixed now.

**Closed** 2015-07-26 04:00 UTC
Labels: 3 - Done, Accepted, Bug-Blocker
