### ISSUE TITLE
Frontend Studies List Display: Some kind of selection memory

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#523] opened 2015-03-22 22:22 UTC
This may be somehow related to #516
Please test on your site:
Landing page; select serie 'Romans' -> A list of studies with serie=Romans are displayed
Then clicking on the menue item 'Studies List' still get the same list; I expect the list of all studies

**Comment by bcordis** [comment] 2015-05-10 16:41
@st-anton do you have cache turned on? Not able to see the error.

**Comment by st-anton** [comment] 2015-05-16 09:05
It happens in my site, but you can see it on Tom's page as well:
http://joomlaoregon.com/jbs/index.php/studies-list
Steps:
- clear cache of the browser
- go to 'studies list'
- make sure, that there is no filter active
- clear browser cache again
- select 'landing page'
- select a series, e.g. Romans or Colossians
- go to 'studies list'

**Comment by bcordis** [comment] 2015-05-16 16:50
@st-anton @tomfuller2 Ok i see the error looking at a solution.

**Comment by bcordis** [comment] 2015-06-24 11:32
Needs to be tested.

**Comment by bcordis** [comment] 2015-07-01 23:32
Closing unless we can reproduce it. Right now I can't after patch

**Comment by st-anton** [comment] 2015-07-08 21:22
It's still present with the current code

**Comment by tomfuller2** [comment] 2015-11-01 00:05
I did some work on fixing this problem. The $state variable seems persistent unless reset. I created a way for the sermons view to know if it is coming from the landing page and changed the Request variable names for landing page. It appears to work but there might be some strange thing happening now with a book query coming through so please test!
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/ff340200139ac71007126f1f86fae4b37d9b6a71

**Comment by bcordis** [comment] 2015-11-17 00:43
@tomfuller2 Last bug to test and we will be stable.

**Comment by tomfuller2** [comment] 2015-11-17 06:13
I believe I fixed this but it may cause problems with the landing page. We
do need to test indeed

**Comment by bcordis** [comment] 2016-02-22 23:19
Tested and seems to be working. Closing for now.

**Closed by bcordis** 2016-02-22 23:19 UTC
Labels: 2 - Working, Accepted, Awaiting Feedback, Bug-Critical
