### ISSUE TITLE
Selecting a file for restore does not work

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#527] opened 2015-03-27 15:05 UTC
Admin - backup and restore - browse for a file. Click submit: "No file selected"

**Comment by bcordis** [comment] 2015-05-17 00:16
@tomfuller2 is this still happening?

**Comment by bcordis** [comment] 2015-05-30 19:35
@tomfuller2 I'm not able to reproduce this. can you please retest?

**Comment by bcordis** [comment] 2015-05-30 19:38
@st-anton also could you test. Next version we are looking at removing this view. it is a duplicate almost of migrate.
@tomfuller2

**Comment by st-anton** [comment] 2015-05-31 16:01
Works on my machine.
I agree: It would be fine to have one combined import function for old (migration) and actual (restore) db, if it is not too much effort.

**Comment by bcordis** [comment] 2015-07-01 23:43
Fixed. Closing as will make new ticket when change.

**Closed by bcordis** 2015-07-01 23:43 UTC
Labels: 3 - Done, Accepted, bug
