### ISSUE TITLE
Backend new media: Addon language cannot be loaded

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#590] opened 2015-06-28 16:10 UTC
Right after clicking on 'new', the message appears:
An error has occurred. 0 Addon language could not be loaded

**Comment by bcordis** [comment] 2015-07-24 03:25
Can you retest this. I'm not able to reproduce this on a clean install. Also put down steups that you took after task=admin.dbreset to get the error.

**Comment by bcordis** [comment] 2015-07-25 12:54
@st-anton @tomfuller2 @genu This is do to the default server not being set in admin. Will need to find a fix for this on new install and on migration.

**Comment by bcordis** [comment] 2015-07-27 01:50
This will be fixed on setting defaults for new install and for migration. Closing as this is in migration and will be set on final creation of defaults.

**Closed by bcordis** 2015-07-27 01:50 UTC
Labels: 3 - Done, Accepted, Bug-Blocker

**Comment by st-anton** [comment] 2015-08-17 23:34
Works as expected
