### ISSUE TITLE
Title of uploaded file incorrect

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#706] opened 2016-10-20 18:35 UTC
From a user: 
I’ve been trying for awhile now getting JBS 9 to work on a local dev site.

I upgraded from version 8 to 9. Upgrade itself worked well but some things aren’t working for me.

Problems I keep having:
1. When uploading new studies it saves the files as filename-MP3 and no extension. So I manually remove the MP3 and add the extension. Then it will play in the front end.
2. Downloading and mp3 file from front end doesn’t work correctly for me. It downloads the file but it’s empty. 0 kb’s in size.

Not sure if his problem 1 is correct so need to test

**Comment by bcordis** [comment] 2016-11-04 03:59
Duplicate of #709

**Comment by bcordis** [comment] 2016-11-04 04:00
Fixed in #709

**Comment by bcordis** [comment] 2016-11-04 04:01
@tomfuller2 Can you verify that the download problem is sill active?

**Comment by tomfuller2** [comment] 2016-11-04 18:17
Can't test until upload works.

**Comment by bcordis** [comment] 2016-11-05 13:25
Fixed with upload test.

**Closed by bcordis** 2016-11-05 13:25 UTC
Labels: Awaiting Feedback, Bug-Major
